### PR TITLE
Word cloud doesn't work if the vector contain \n. Replace \n with space.

### PR DESCRIPTION
**Pull request by ghost**
Hi @XD-DENG , I notice the word cloud doesn't work if the vector contains \n.
Just a suggestion to replace the \n with space, even though the user supposes to remove or split the \n first before "renderWordcloud".

### CODE REVIEW

**Comment by XD-DENG** [comment]
@chinyong-lim Hi CY, may you change the version number in DESCRIPTION 0.2.13? before I merge. 
Thanks!

**Review by XD-DENG — APPROVED** [review]
The bug listed does exist and the commit can solve.

**Comment by ghost** [comment]
Hi @XD-DENG , DESCRIPTION and NEWS changed.
You may go ahead and merge the changes ;-)

**Comment by XD-DENG** [comment]
Thanks @chinyong-lim

**Pull request merged**
